### ISSUE TITLE
Broken GitHub link

### ISSUE THREAD

**Issue by jbduncan** [junit-pioneer/junit-pioneer.github.io#2]
On the home page (http://junit-pioneer.org/), if one clicks on the GitHub icon at the very bottom (the one with the link https://github.com/junit-jupiter), it leads to a 404 page.

I presume that the fix for this would be to redirect to https://github.com/junit-pioneer/junit-pioneer.

**Comment by nipafx** [comment]
A mere two and a half years later, I looked into this. It looks like the problem was already fixed - the link now goes to https://github.com/junit-pioneer (the org page) - it's deliberately not https://github.com/junit-pioneer/junit-pioneer (the project page) because it should link to "Everything Pioneer".

**Comment by jbduncan** [comment]
@nicolaiparlog Brilliant! I can confirm on my end that clicking on the GitHub icon indeed loads up the JUnit Pioneer org page.

Thank you for looking into this. 👍
